name: is_inn
description: Проверка валидности ИНН
version: 1.0.0
author: Kirill Matrosov
homepage: https://github.com/kdmatrosov/is_inn

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

